// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pprkbxgdimqfjrbhoseb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwcmtieGdkaW1xZmpyYmhvc2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMjUyODQsImV4cCI6MjA1ODYwMTI4NH0.eCM0-Fs3wcFBtXv1EaYNw7TXm9p3Ac9R8kXLxAlOyDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);